# Generated by Django 2.0.6 on 2018-07-05 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('StaffId', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('Role', models.CharField(blank=True, choices=[('A', 'Admin'), ('T', 'Transport Manager'), ('F', 'FleetAssistant'), ('D', 'Department Head'), ('M', 'Mechanic Supervisor')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('Contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='invalid mobile number', regex='^\\d+$')])),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
    ]
