# Generated by Django 2.0.6 on 2018-06-23 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('staffId', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='invalid mobile number', regex='^\\d+$')])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
