# Generated by Django 2.0.6 on 2018-07-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='Availability',
            field=models.BooleanField(default=True),
        ),
    ]
