# Generated by Django 2.0.6 on 2018-07-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_vehicles_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Travel_date',
            field=models.DateField(),
        ),
    ]
