# Generated by Django 2.0.6 on 2018-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180706_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Travellers_desc',
            field=models.CharField(max_length=50),
        ),
    ]
